"""
Database Layer - SQLite storage for all trading data.
Stores: candles (OHLCV), whale events, trades, positions, signals.
"""

import sqlite3
import os
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any
from core.interfaces.database_port import IDatabase


class SqliteRepository(IDatabase):
    """SQLite database implementing the IDatabase port."""

    def __init__(self, db_path: str = "trading_agent.db"):
        self.db_path = db_path
        # Increase timeout and use WAL mode for better concurrency
        self.conn = sqlite3.connect(db_path, check_same_thread=False, timeout=30)
        self.conn.row_factory = sqlite3.Row
        self._enable_wal_mode()
        self._create_tables()

    def _enable_wal_mode(self):
        """Enable Write-Ahead Logging for better concurrency."""
        with self.conn:
            self.conn.execute("PRAGMA journal_mode=WAL")
            self.conn.execute("PRAGMA synchronous=NORMAL")

    def _create_tables(self):
        """Create all required tables if they don't exist."""
        cursor = self.conn.cursor()

        # OHLCV Candle data
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS candles (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL,
                timestamp INTEGER NOT NULL,
                open REAL NOT NULL,
                high REAL NOT NULL,
                low REAL NOT NULL,
                close REAL NOT NULL,
                volume REAL NOT NULL,
                fetched_at TEXT NOT NULL,
                UNIQUE(symbol, timeframe, timestamp)
            )
        """)

        # Volume anomalies (huge trades or orderbook walls)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS volume_anomalies (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                anomaly_type TEXT NOT NULL,
                side TEXT NOT NULL,
                amount REAL NOT NULL,
                price REAL NOT NULL,
                amount_usd REAL NOT NULL,
                z_score REAL NOT NULL,
                timestamp INTEGER NOT NULL,
                fetched_at TEXT NOT NULL
            )
        """)

        # Trading signals generated by analysis
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL,
                signal_type TEXT NOT NULL,
                technical_trend TEXT,
                technical_momentum TEXT,
                technical_confidence REAL,
                volume_flow TEXT,
                volume_intensity TEXT,
                volume_confidence REAL,
                combined_action TEXT NOT NULL,
                combined_confidence REAL NOT NULL,
                ai_decision TEXT,
                ai_reasoning TEXT,
                created_at TEXT NOT NULL
            )
        """)

        # Executed trades (paper or live)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS trades (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                side TEXT NOT NULL,
                order_type TEXT NOT NULL,
                price REAL NOT NULL,
                amount REAL NOT NULL,
                cost REAL NOT NULL,
                stop_loss REAL,
                take_profit REAL,
                status TEXT NOT NULL DEFAULT 'open',
                mode TEXT NOT NULL DEFAULT 'paper',
                signal_id INTEGER,
                opened_at TEXT NOT NULL,
                closed_at TEXT,
                close_price REAL,
                highest_price REAL,
                max_drawdown REAL,
                pnl REAL,
                pnl_percent REAL,
                close_reason TEXT,
                reasoning TEXT,
                FOREIGN KEY (signal_id) REFERENCES signals(id)
            )
        """)

        # Portfolio snapshots
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS portfolio_snapshots (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                total_equity REAL NOT NULL,
                available_balance REAL NOT NULL,
                unrealized_pnl REAL NOT NULL,
                realized_pnl_today REAL NOT NULL,
                open_positions INTEGER NOT NULL,
                snapshot_at TEXT NOT NULL
            )
        """)

        self.conn.commit()

    # ──────────────────────────────── Candles ────────────────────────────────

    def save_candles(self, symbol: str, timeframe: str, candles: List[List]):
        """Save OHLCV candles. candles = [[timestamp, O, H, L, C, V], ...]"""
        now = datetime.now(timezone.utc).isoformat()
        with self.conn:
            cursor = self.conn.cursor()
            for c in candles:
                cursor.execute("""
                    INSERT OR REPLACE INTO candles 
                    (symbol, timeframe, timestamp, open, high, low, close, volume, fetched_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (symbol, timeframe, c[0], c[1], c[2], c[3], c[4], c[5], now))

    def get_candles(self, symbol: str, timeframe: str, limit: int = 200) -> List[Dict]:
        """Get latest candles for a symbol/timeframe."""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT timestamp, open, high, low, close, volume
            FROM candles
            WHERE symbol = ? AND timeframe = ?
            ORDER BY timestamp DESC
            LIMIT ?
        """, (symbol, timeframe, limit))
        rows = cursor.fetchall()
        return [dict(r) for r in reversed(rows)]

    # ──────────────────────────────── Volume Anomalies ────────────────────────────────

    def save_volume_anomaly(self, event: Dict[str, Any]):
        """Save a single volume anomaly event."""
        now = datetime.now(timezone.utc).isoformat()
        with self.conn:
            cursor = self.conn.cursor()
            cursor.execute("""
                INSERT INTO volume_anomalies
                (symbol, anomaly_type, side, amount, price, amount_usd, z_score, timestamp, fetched_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                event["symbol"], event["anomaly_type"], event["side"],
                event["amount"], event["price"], event["amount_usd"], 
                event.get("z_score", 0.0), event["timestamp"], now
            ))

    def get_volume_anomalies(self, symbol: str, since_timestamp: int) -> List[Dict]:
        """Get volume anomalies for a symbol since a given timestamp."""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT * FROM volume_anomalies
            WHERE symbol = ? AND timestamp >= ?
            ORDER BY timestamp DESC
        """, (symbol, since_timestamp))
        return [dict(r) for r in cursor.fetchall()]

    # ──────────────────────────────── Signals ────────────────────────────────

    def save_signal(self, signal: Dict[str, Any]) -> int:
        """Save a trading signal and return its ID."""
        now = datetime.now(timezone.utc).isoformat()
        with self.conn:
            cursor = self.conn.cursor()
            cursor.execute("""
                INSERT INTO signals
                (symbol, timeframe, signal_type, technical_trend, technical_momentum,
                 technical_confidence, volume_flow, volume_intensity, volume_confidence,
                 combined_action, combined_confidence, ai_decision, ai_reasoning, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                signal["symbol"], signal["timeframe"], signal.get("signal_type", "analysis"),
                signal.get("technical_trend"), signal.get("technical_momentum"),
                signal.get("technical_confidence"),
                signal.get("volume_flow"), signal.get("volume_intensity"),
                signal.get("volume_confidence"),
                signal["combined_action"], signal["combined_confidence"],
                signal.get("ai_decision"), signal.get("ai_reasoning"),
                now
            ))
            return cursor.lastrowid

    def get_recent_signals(self, limit: int = 10) -> List[Dict]:
        """Get the most recent signals."""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT * FROM signals
            ORDER BY created_at DESC
            LIMIT ?
        """, (limit,))
        return [dict(r) for r in cursor.fetchall()]

    # ──────────────────────────────── Trades ────────────────────────────────

    def save_trade(self, trade: Dict[str, Any]) -> int:
        """Save a new trade and return its ID."""
        with self.conn:
            cursor = self.conn.cursor()
            cursor.execute("""
                INSERT INTO trades
                (symbol, side, order_type, price, amount, cost,
                 stop_loss, take_profit, highest_price, max_drawdown, status, mode, signal_id, reasoning, opened_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                trade["symbol"], trade["side"], trade["order_type"],
                trade["price"], trade["amount"], trade["cost"],
                trade.get("stop_loss"), trade.get("take_profit"),
                trade["price"], 0.0, # initial highest_price is entry price, max_drawdown is 0.0
                trade.get("status", "open"), trade.get("mode", "paper"),
                trade.get("signal_id"), trade.get("reasoning", ""), datetime.now(timezone.utc).isoformat()
            ))
            return cursor.lastrowid

    def close_trade(self, trade_id: int, close_price: float, reason: str):
        """Close a trade with final P&L calculation."""
        with self.conn:
            cursor = self.conn.cursor()
            # Get the original trade
            cursor.execute("SELECT * FROM trades WHERE id = ?", (trade_id,))
            trade = dict(cursor.fetchone())

            # Calculate P&L
            if trade["side"] == "buy":
                pnl = (close_price - trade["price"]) * trade["amount"]
            else:
                pnl = (trade["price"] - close_price) * trade["amount"]

            pnl_percent = (pnl / trade["cost"]) * 100 if trade["cost"] > 0 else 0

            cursor.execute("""
                UPDATE trades SET
                    status = 'closed', closed_at = ?, close_price = ?,
                    pnl = ?, pnl_percent = ?, close_reason = ?
                WHERE id = ?
            """, (datetime.now(timezone.utc).isoformat(), close_price, pnl, pnl_percent, reason, trade_id))

    def get_open_trades(self, symbol: Optional[str] = None) -> List[Dict]:
        """Get all open trades, optionally filtered by symbol."""
        cursor = self.conn.cursor()
        if symbol:
            cursor.execute(
                "SELECT * FROM trades WHERE status = 'open' AND symbol = ?", (symbol,))
        else:
            cursor.execute("SELECT * FROM trades WHERE status = 'open'")
        return [dict(r) for r in cursor.fetchall()]

    def update_trade_highest_price(self, trade_id: int, highest_price: float):
        """Update the highest price recorded for an open trade."""
        with self.conn:
            cursor = self.conn.cursor()
            cursor.execute("""
                UPDATE trades SET highest_price = ?
                WHERE id = ?
            """, (highest_price, trade_id))

    def get_trades_today(self) -> List[Dict]:
        """Get all trades opened today (for drawdown calculation)."""
        cursor = self.conn.cursor()
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        cursor.execute(
            "SELECT * FROM trades WHERE opened_at LIKE ?", (f"{today}%",))
        return [dict(r) for r in cursor.fetchall()]

    # ──────────────────────────────── Portfolio ────────────────────────────────

    def save_portfolio_snapshot(self, snapshot: Dict[str, Any]):
        """Save a portfolio snapshot."""
        cursor = self.conn.cursor()
        cursor.execute("""
            INSERT INTO portfolio_snapshots
            (total_equity, available_balance, unrealized_pnl,
             realized_pnl_today, open_positions, snapshot_at)
            VALUES (?, ?, ?, ?, ?, ?)
        """, (
            snapshot["total_equity"], snapshot["available_balance"],
            snapshot["unrealized_pnl"], snapshot["realized_pnl_today"],
            snapshot["open_positions"], datetime.now(timezone.utc).isoformat()
        ))
        self.conn.commit()

    def get_latest_portfolio_snapshot(self) -> Optional[Dict]:
        """Get the most recent portfolio snapshot."""
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT * FROM portfolio_snapshots
            ORDER BY snapshot_at DESC
            LIMIT 1
        """)
        row = cursor.fetchone()
        return dict(row) if row else None

    def close(self):
        """Close the database connection."""
        self.conn.close()
