"""
Supabase PostgreSQL Database Layer - Cloud storage for all trading data.
Implements the IDatabase port using psycopg2.
"""

import time
import psycopg2
from psycopg2.extras import RealDictCursor
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any
from core.interfaces.database_port import IDatabase
from utils.logger import get_logger

logger = get_logger(__name__)


class SupabaseRepository(IDatabase):
    """Supabase PostgreSQL database implementing the IDatabase port."""

    def __init__(self, db_url: str):
        self.db_url = db_url
        self.conn = None
        self._connect()
        self._create_tables()

    def _connect(self):
        """Establish connection to Supabase PostgreSQL database."""
        if not self.db_url or "project-id" in self.db_url:
            logger.warning("⚠️ SUPABASE_DB_URL is not configured properly in .env! Database connection skipped.")
            return

        try:
            self.conn = psycopg2.connect(self.db_url)
            self.conn.autocommit = True
            logger.info("🔌 Connected to Supabase PostgreSQL database successfully.")
        except Exception as e:
            logger.error(f"❌ Failed to connect to Supabase: {e}")
            raise e

    def _create_tables(self):
        """Create all required tables if they don't exist in PostgreSQL."""
        if not self.conn:
            return

        try:
            with self.conn.cursor() as cursor:
                # OHLCV Candle data
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS candles (
                        id SERIAL PRIMARY KEY,
                        symbol VARCHAR(50) NOT NULL,
                        timeframe VARCHAR(10) NOT NULL,
                        timestamp BIGINT NOT NULL,
                        open DOUBLE PRECISION NOT NULL,
                        high DOUBLE PRECISION NOT NULL,
                        low DOUBLE PRECISION NOT NULL,
                        close DOUBLE PRECISION NOT NULL,
                        volume DOUBLE PRECISION NOT NULL,
                        fetched_at VARCHAR(100) NOT NULL,
                        UNIQUE(symbol, timeframe, timestamp)
                    )
                """)

                # Volume anomalies (huge trades or orderbook walls)
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS volume_anomalies (
                        id SERIAL PRIMARY KEY,
                        symbol VARCHAR(50) NOT NULL,
                        anomaly_type VARCHAR(50) NOT NULL,
                        side VARCHAR(10) NOT NULL,
                        amount DOUBLE PRECISION NOT NULL,
                        price DOUBLE PRECISION NOT NULL,
                        amount_usd DOUBLE PRECISION NOT NULL,
                        z_score DOUBLE PRECISION NOT NULL,
                        timestamp BIGINT NOT NULL,
                        fetched_at VARCHAR(100) NOT NULL
                    )
                """)

                # Trading signals generated by analysis
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS signals (
                        id SERIAL PRIMARY KEY,
                        symbol VARCHAR(50) NOT NULL,
                        timeframe VARCHAR(10) NOT NULL,
                        signal_type VARCHAR(50) NOT NULL,
                        technical_trend VARCHAR(20),
                        technical_momentum VARCHAR(20),
                        technical_confidence DOUBLE PRECISION,
                        volume_flow VARCHAR(20),
                        volume_intensity VARCHAR(20),
                        volume_confidence DOUBLE PRECISION,
                        combined_action VARCHAR(20) NOT NULL,
                        combined_confidence DOUBLE PRECISION NOT NULL,
                        ai_decision VARCHAR(20),
                        ai_reasoning TEXT,
                        created_at VARCHAR(100) NOT NULL
                    )
                """)

                # Executed trades (paper or live)
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS trades (
                        id SERIAL PRIMARY KEY,
                        symbol VARCHAR(50) NOT NULL,
                        side VARCHAR(10) NOT NULL,
                        order_type VARCHAR(20) NOT NULL,
                        price DOUBLE PRECISION NOT NULL,
                        amount DOUBLE PRECISION NOT NULL,
                        cost DOUBLE PRECISION NOT NULL,
                        stop_loss DOUBLE PRECISION,
                        take_profit DOUBLE PRECISION,
                        status VARCHAR(20) NOT NULL DEFAULT 'open',
                        mode VARCHAR(20) NOT NULL DEFAULT 'paper',
                        signal_id INTEGER,
                        opened_at VARCHAR(100) NOT NULL,
                        closed_at VARCHAR(100),
                        close_price DOUBLE PRECISION,
                        highest_price DOUBLE PRECISION,
                        max_drawdown DOUBLE PRECISION,
                        pnl DOUBLE PRECISION,
                        pnl_percent DOUBLE PRECISION,
                        close_reason VARCHAR(100),
                        reasoning TEXT,
                        FOREIGN KEY (signal_id) REFERENCES signals(id)
                    )
                """)

                # Portfolio snapshots
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS portfolio_snapshots (
                        id SERIAL PRIMARY KEY,
                        total_equity DOUBLE PRECISION NOT NULL,
                        available_balance DOUBLE PRECISION NOT NULL,
                        unrealized_pnl DOUBLE PRECISION NOT NULL,
                        realized_pnl_today DOUBLE PRECISION NOT NULL,
                        open_positions INTEGER NOT NULL,
                        snapshot_at VARCHAR(100) NOT NULL
                    )
                """)
            logger.info("✅ Database tables verified/created on Supabase.")
        except Exception as e:
            logger.error(f"❌ Failed to verify tables on Supabase: {e}")
            raise e

    def _get_cursor(self):
        """Helper to get a dict-based cursor."""
        if not self.conn or self.conn.closed:
            self._connect()
        return self.conn.cursor(cursor_factory=RealDictCursor)

    # ──────────────────────────────── Candles ────────────────────────────────

    def save_candles(self, symbol: str, timeframe: str, candles: List[List]):
        """Save OHLCV candles with ON CONFLICT resolution in PostgreSQL."""
        if not self.conn:
            return
        now = datetime.now(timezone.utc).isoformat()
        try:
            with self.conn.cursor() as cursor:
                for c in candles:
                    cursor.execute("""
                        INSERT INTO candles 
                        (symbol, timeframe, timestamp, open, high, low, close, volume, fetched_at)
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                        ON CONFLICT (symbol, timeframe, timestamp) 
                        DO UPDATE SET 
                            open=EXCLUDED.open, 
                            high=EXCLUDED.high, 
                            low=EXCLUDED.low, 
                            close=EXCLUDED.close, 
                            volume=EXCLUDED.volume, 
                            fetched_at=EXCLUDED.fetched_at
                    """, (symbol, timeframe, int(c[0]), float(c[1]), float(c[2]), float(c[3]), float(c[4]), float(c[5]), now))
        except Exception as e:
            logger.error(f"❌ Supabase save_candles error: {e}")

    def get_candles(self, symbol: str, timeframe: str, limit: int = 200) -> List[Dict]:
        """Get latest candles from Supabase."""
        if not self.conn:
            return []
        try:
            with self._get_cursor() as cursor:
                cursor.execute("""
                    SELECT timestamp, open, high, low, close, volume
                    FROM candles
                    WHERE symbol = %s AND timeframe = %s
                    ORDER BY timestamp DESC
                    LIMIT %s
                """, (symbol, timeframe, limit))
                rows = cursor.fetchall()
                return [dict(r) for r in reversed(rows)]
        except Exception as e:
            logger.error(f"❌ Supabase get_candles error: {e}")
            return []

    # ──────────────────────────────── Volume Anomalies ────────────────────────────────

    def save_volume_anomaly(self, event: Dict[str, Any]):
        """Save a single volume anomaly event."""
        if not self.conn:
            return
        now = datetime.now(timezone.utc).isoformat()
        try:
            with self.conn.cursor() as cursor:
                cursor.execute("""
                    INSERT INTO volume_anomalies
                    (symbol, anomaly_type, side, amount, price, amount_usd, z_score, timestamp, fetched_at)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                """, (
                    event["symbol"], event["anomaly_type"], event["side"],
                    float(event["amount"]), float(event["price"]), float(event["amount_usd"]), 
                    float(event.get("z_score", 0.0)), int(event["timestamp"]), now
                ))
        except Exception as e:
            logger.error(f"❌ Supabase save_volume_anomaly error: {e}")

    def get_volume_anomalies(self, symbol: str, since_timestamp: int) -> List[Dict]:
        """Get volume anomalies since a timestamp."""
        if not self.conn:
            return []
        try:
            with self._get_cursor() as cursor:
                cursor.execute("""
                    SELECT * FROM volume_anomalies
                    WHERE symbol = %s AND timestamp >= %s
                    ORDER BY timestamp DESC
                """, (symbol, since_timestamp))
                return [dict(r) for r in cursor.fetchall()]
        except Exception as e:
            logger.error(f"❌ Supabase get_volume_anomalies error: {e}")
            return []

    # ──────────────────────────────── Signals ────────────────────────────────

    def save_signal(self, signal: Dict[str, Any]) -> int:
        """Save a trading signal and return its ID using RETURNING clause."""
        if not self.conn:
            return 0
        now = datetime.now(timezone.utc).isoformat()
        try:
            with self.conn.cursor() as cursor:
                cursor.execute("""
                    INSERT INTO signals
                    (symbol, timeframe, signal_type, technical_trend, technical_momentum,
                     technical_confidence, volume_flow, volume_intensity, volume_confidence,
                     combined_action, combined_confidence, ai_decision, ai_reasoning, created_at)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING id
                """, (
                    signal["symbol"], signal["timeframe"], signal.get("signal_type", "analysis"),
                    signal.get("technical_trend"), signal.get("technical_momentum"),
                    float(signal.get("technical_confidence") or 0.0),
                    signal.get("volume_flow"), signal.get("volume_intensity"),
                    float(signal.get("volume_confidence") or 0.0),
                    signal["combined_action"], float(signal["combined_confidence"]),
                    signal.get("ai_decision"), signal.get("ai_reasoning"),
                    now
                ))
                return cursor.fetchone()[0]
        except Exception as e:
            logger.error(f"❌ Supabase save_signal error: {e}")
            return 0

    def get_recent_signals(self, limit: int = 10) -> List[Dict]:
        """Get the most recent signals."""
        if not self.conn:
            return []
        try:
            with self._get_cursor() as cursor:
                cursor.execute("""
                    SELECT * FROM signals
                    ORDER BY created_at DESC
                    LIMIT %s
                """, (limit,))
                return [dict(r) for r in cursor.fetchall()]
        except Exception as e:
            logger.error(f"❌ Supabase get_recent_signals error: {e}")
            return []

    # ──────────────────────────────── Trades ────────────────────────────────

    def save_trade(self, trade: Dict[str, Any]) -> int:
        """Save a new trade and return its ID using RETURNING."""
        if not self.conn:
            return 0
        try:
            with self.conn.cursor() as cursor:
                cursor.execute("""
                    INSERT INTO trades
                    (symbol, side, order_type, price, amount, cost,
                     stop_loss, take_profit, highest_price, max_drawdown, status, mode, signal_id, reasoning, opened_at)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING id
                """, (
                    trade["symbol"], trade["side"], trade["order_type"],
                    float(trade["price"]), float(trade["amount"]), float(trade["cost"]),
                    float(trade["stop_loss"]) if trade.get("stop_loss") else None,
                    float(trade["take_profit"]) if trade.get("take_profit") else None,
                    float(trade["price"]), 0.0,
                    trade.get("status", "open"), trade.get("mode", "paper"),
                    trade.get("signal_id"), trade.get("reasoning", ""), 
                    datetime.now(timezone.utc).isoformat()
                ))
                return cursor.fetchone()[0]
        except Exception as e:
            logger.error(f"❌ Supabase save_trade error: {e}")
            return 0

    def close_trade(self, trade_id: int, close_price: float, reason: str):
        """Close a trade with final P&L calculation."""
        if not self.conn:
            return
        try:
            # 1. Fetch trade using cursor
            with self._get_cursor() as dict_cursor:
                dict_cursor.execute("SELECT * FROM trades WHERE id = %s", (trade_id,))
                row = dict_cursor.fetchone()
                if not row:
                    logger.error(f"❌ Trade with id {trade_id} not found in Supabase.")
                    return
                trade = dict(row)

            # 2. Calculate PnL
            if trade["side"] == "buy":
                pnl = (close_price - float(trade["price"])) * float(trade["amount"])
            else:
                pnl = (float(trade["price"]) - close_price) * float(trade["amount"])

            pnl_percent = (pnl / float(trade["cost"])) * 100 if float(trade["cost"]) > 0 else 0

            with self.conn.cursor() as cursor:
                cursor.execute("""
                    UPDATE trades SET
                        status = 'closed', closed_at = %s, close_price = %s,
                        pnl = %s, pnl_percent = %s, close_reason = %s
                    WHERE id = %s
                """, (datetime.now(timezone.utc).isoformat(), float(close_price), float(pnl), float(pnl_percent), reason, trade_id))
        except Exception as e:
            logger.error(f"❌ Supabase close_trade error: {e}")

    def get_open_trades(self, symbol: Optional[str] = None) -> List[Dict]:
        """Get all open trades."""
        if not self.conn:
            return []
        try:
            with self._get_cursor() as cursor:
                if symbol:
                    cursor.execute("SELECT * FROM trades WHERE status = 'open' AND symbol = %s", (symbol,))
                else:
                    cursor.execute("SELECT * FROM trades WHERE status = 'open'")
                return [dict(r) for r in cursor.fetchall()]
        except Exception as e:
            logger.error(f"❌ Supabase get_open_trades error: {e}")
            return []

    def update_trade_highest_price(self, trade_id: int, highest_price: float):
        """Update the highest price recorded for an open trade."""
        if not self.conn:
            return
        try:
            with self.conn.cursor() as cursor:
                cursor.execute("""
                    UPDATE trades SET highest_price = %s
                    WHERE id = %s
                """, (float(highest_price), trade_id))
        except Exception as e:
            logger.error(f"❌ Supabase update_trade_highest_price error: {e}")

    def get_trades_today(self) -> List[Dict]:
        """Get all trades opened today."""
        if not self.conn:
            return []
        try:
            with self._get_cursor() as cursor:
                today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
                cursor.execute("SELECT * FROM trades WHERE opened_at LIKE %s", (f"{today}%",))
                return [dict(r) for r in cursor.fetchall()]
        except Exception as e:
            logger.error(f"❌ Supabase get_trades_today error: {e}")
            return []

    # ──────────────────────────────── Portfolio ────────────────────────────────

    def save_portfolio_snapshot(self, snapshot: Dict[str, Any]):
        """Save a portfolio snapshot."""
        if not self.conn:
            return
        try:
            with self.conn.cursor() as cursor:
                cursor.execute("""
                    INSERT INTO portfolio_snapshots
                    (total_equity, available_balance, unrealized_pnl,
                     realized_pnl_today, open_positions, snapshot_at)
                    VALUES (%s, %s, %s, %s, %s, %s)
                """, (
                    float(snapshot["total_equity"]), float(snapshot["available_balance"]),
                    float(snapshot["unrealized_pnl"]), float(snapshot["realized_pnl_today"]),
                    int(snapshot["open_positions"]), datetime.now(timezone.utc).isoformat()
                ))
        except Exception as e:
            logger.error(f"❌ Supabase save_portfolio_snapshot error: {e}")

    def get_latest_portfolio_snapshot(self) -> Optional[Dict]:
        """Get the most recent portfolio snapshot."""
        if not self.conn:
            return None
        try:
            with self._get_cursor() as cursor:
                cursor.execute("""
                    SELECT * FROM portfolio_snapshots
                    ORDER BY snapshot_at DESC
                    LIMIT 1
                """, ())
                row = cursor.fetchone()
                return dict(row) if row else None
        except Exception as e:
            logger.error(f"❌ Supabase get_latest_portfolio_snapshot error: {e}")
            return None

    def close(self):
        """Close the connection."""
        if self.conn and not self.conn.closed:
            self.conn.close()
            logger.info("🔌 Supabase PostgreSQL connection closed.")
